import { StructuredToolInterface } from '@langchain/core/tools';
import {
  getFootballMatchSchedule,
  getFootballMatchOdds,
  getFootballTeamStats,
  getFootballRecentForm,
  getFootballFixtureStatistics,
  getFootballFixtureEvents,
  getFootballFixtureLineups,
  getFootballFixturePlayers,
  getFootballHeadToHead,
  getFootballStandings,
  getFootballInjuries,
  getFootballPredictions,
  getFootballLeagues,
  getFootballTeams,
  getFootballPlayers,
  getFootballPlayerProfiles,
  getFootballPlayerSeasons,
  getFootballPlayerSquads,
  getFootballTopScorers,
  getFootballTopAssists,
  getFootballTopYellowCards,
  getFootballTopRedCards,
  getFootballTransfers,
  getFootballTrophies,
  getFootballSidelined,
  getFootballOddsMapping,
  getFootballOddsBets,
  getFootballOddsBookmakers,
} from './sports/index.js';
import { tavilySearch } from './search/index.js';

export const TOOLS: StructuredToolInterface[] = [
  getFootballMatchSchedule,
  getFootballMatchOdds,
  getFootballTeamStats,
  getFootballRecentForm,
  getFootballFixtureStatistics,
  getFootballFixtureEvents,
  getFootballFixtureLineups,
  getFootballFixturePlayers,
  getFootballHeadToHead,
  getFootballStandings,
  getFootballInjuries,
  getFootballPredictions,
  getFootballLeagues,
  getFootballTeams,
  getFootballPlayers,
  getFootballPlayerProfiles,
  getFootballPlayerSeasons,
  getFootballPlayerSquads,
  getFootballTopScorers,
  getFootballTopAssists,
  getFootballTopYellowCards,
  getFootballTopRedCards,
  getFootballTransfers,
  getFootballTrophies,
  getFootballSidelined,
  getFootballOddsMapping,
  getFootballOddsBets,
  getFootballOddsBookmakers,
  ...(process.env.TAVILY_API_KEY ? [tavilySearch] : []),
];

export {
  getFootballMatchSchedule,
  getFootballMatchOdds,
  getFootballTeamStats,
  getFootballRecentForm,
  getFootballFixtureStatistics,
  getFootballFixtureEvents,
  getFootballFixtureLineups,
  getFootballFixturePlayers,
  getFootballHeadToHead,
  getFootballStandings,
  getFootballInjuries,
  getFootballPredictions,
  getFootballLeagues,
  getFootballTeams,
  getFootballPlayers,
  getFootballPlayerProfiles,
  getFootballPlayerSeasons,
  getFootballPlayerSquads,
  getFootballTopScorers,
  getFootballTopAssists,
  getFootballTopYellowCards,
  getFootballTopRedCards,
  getFootballTransfers,
  getFootballTrophies,
  getFootballSidelined,
  getFootballOddsMapping,
  getFootballOddsBets,
  getFootballOddsBookmakers,
  tavilySearch,
};
